apiVersion: apps/v1
kind: Deployment
metadata:
  name: check-deployment
  labels:                    
    app: deploy
spec:
  replicas: 1
  selector:
    matchLabels:             
      app: app
  template:
    metadata:                
      labels: 
        app: app
    spec:
      containers:
        - name: demo-image
          image: sunkarisomasekhar/demo-image:v1
          ports:
            - containerPort: 8090
          resources:          
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
